targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/*.dart
        options:
          # Generates a copyWith method
          copy_with: true
          # Generates an == operator and a hashCode method
          equal: true
          # Generates a toString method
          to_string: true
          # Generates fromJson/toJson methods
          from_json: true
          to_json: true
      
      hive_generator:
        generate_for:
          - lib/**/*.dart
        options:
          auto_generate_ignore_for_tests: true
      
      cloud_firestore_odm_generator:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/*
            - lib/**
        options:
          create_field_map: true
          create_per_field_to_json: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - 'type=lint'
      
      reactive_forms_generator:
        generate_for:
          - lib/**/*.dart
