targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/*.dart
        options:
          # Generates a copyWith method
          copy_with: true
          # Generates an == operator and a hashCode method
          equal: true
          # Generates a toString method
          to_string: true
          # Generates fromJson/toJson methods
          from_json: true
          to_json: true
      
      hive_generator:
        generate_for:
          - lib/**/*.dart
        options:
          auto_generate_ignore_for_tests: true
      
      json_serializable:
        generate_for:
          - lib/**/*.dart
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
      
      reactive_forms_generator:
        generate_for:
          - lib/**/*.dart

      graphql_codegen:
        options:
          clients:
            - graphql_flutter
          scalars:
            DateTime:
              type: DateTime
            JSON:
              type: Object
          generatedFileHeader: |
            // GENERATED CODE - DO NOT MODIFY BY HAND
            // ignore_for_file: type=lint
            // ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
