name: best_buddy_flutter
description: A Flutter app for study buddy - notices and class tests management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  graphql: ^5.2.1
  graphql_flutter: ^5.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^7.0.0
  material_color_utilities: ^0.11.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1  
  path_provider: ^2.1.5
  infinite_scroll_pagination: ^4.1.0
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.1.4
  
  # GraphQL
  # graphql: ^5.1.3
  # graphql_flutter: ^5.1.2
  # graphql_codegen: ^0.13.0
  
  # State Management
  # flutter_bloc: ^8.1.3
  # bloc: ^8.1.2
  # get_it: ^7.6.4
  
  # Forms
  # reactive_forms: ^17.0.1
  # reactive_forms_annotations: ^7.0.0
  
  # Data Persistence
  # hive_ce: ^2.11.3
  # hive_ce_flutter: ^2.3.1
  
  # Code Generation
  # json_annotation: ^4.9.0
  # freezed_annotation: ^3.0.0
  
  # UI & Navigation
  # go_router: ^15.1.2
  # flutter_svg: ^2.0.7
  
  # Date handling
  # intl: ^0.20.2
  
  # Network
  # dio: ^5.3.2
  
  # Notifications
  # firebase_messaging: ^14.7.6
  # flutter_local_notifications: ^16.2.0
    # Utilities
  # equatable: ^2.0.5
  # logger: ^2.0.2+1
  # dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  graphql_codegen: ^1.2.3
  hive_ce_generator: ^1.9.2
  json_serializable: ^6.9.5
  package_rename: ^1.10.0
  reactive_forms_generator: ^7.0.0
  # flutter_lints: ^6.0.0
  
  # Code Generation
  # build_runner: ^2.4.7
  # freezed: ^3.0.6
  # json_serializable: ^6.9.5
  # hive_ce_generator: ^1.9.2
  # reactive_forms_generator: ^7.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  