name: best_buddy_flutter
description: A Flutter app for study buddy - notices and class tests management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # GraphQL
  graphql: ^5.2.1
  graphql_flutter: ^5.2.0
  
  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1  
  hydrated_bloc: ^10.0.0

  # Notifications
  firebase_core: ^3.8.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1

  # Code Generation
  json_annotation: ^4.9.0
  reactive_forms_annotations: ^7.0.0

  # UI & Navigation
  go_router: ^15.1.2
  table_calendar: ^3.2.0
  google_fonts: ^6.2.1
  infinite_scroll_pagination: ^4.1.0

  # Data Persistence
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  # Forms
  

  # Utilities
  intl: ^0.20.2
  get_it: ^8.0.3
  path_provider: ^2.1.5
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.1.4  
  local_auth: ^2.3.0
  timezone: 0.10.1
  cloud_firestore: ^5.6.9
  cloud_firestore_odm: ^1.0.0-dev.88
  firebase_auth: ^5.6.0
  reactive_forms: ^17.0.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  package_rename: ^1.10.0
  
  # Code Generation
  build_runner: ^2.4.15
  reactive_forms_generator: ^5.1.2
  cloud_firestore_odm_generator: ^1.0.0-dev.90
  freezed: ^2.5.7
  hive_ce_generator: ^1.8.1
  json_serializable: ^6.9.0
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  